### ISSUE TITLE
Schedule page layout

### ISSUE THREAD

**Issue by petermcd** [phplondon/phpukconference#17]
The schedule page currently has an issue when viewing on mobiles. The titles of the talks and speakers run of of the page. The page will not allow horizontal scrolling to see the remaining title.

The same issue also exists in portrait mode (obviously for the longer titles). I have attached a screenshot that demonstrates this.

![63402781-dd50-4441-9b95-3cce2195a07a](https://cloud.githubusercontent.com/assets/148006/5111531/1cd2bee2-7019-11e4-94af-8f08167081ad.png)

**Comment by petermcd** [comment]
Just to advise the screen shot was taken in the twitter app however it is the same in Safari.

**Comment by samdb** [comment]
They should expand on click now.
