### ISSUE TITLE
Incorrect Abstract Links?

### ISSUE THREAD

**Issue by levofski** [phplondon/phpukconference#4]
Hi there, on the Schedule page http://phpconference.co.uk/schedule/, I think the "Abstract" link for "RPM'ing your apps and tools" is popping the wrong box. It seems to be the box for "(Re)discovering the SPL".

![image](https://f.cloud.github.com/assets/1890796/1489971/e680f92c-4787-11e3-892d-b9cf73971a7c.png)

Also I think the link for "I've Been Hacked, Now What?" is popping up the box for "Normalisation: Friend or Foe"

![image](https://f.cloud.github.com/assets/1890796/1489987/5f51bc56-4788-11e3-9a63-5232874cc6ac.png)

Also I think the link for "PHP Performance: Under The Hood" is popping up the box for "PHP 5.NEXT: The New Bits"

![image](https://f.cloud.github.com/assets/1890796/1490001/b4bf69e0-4788-11e3-9cc2-8ebfbf992a2f.png)

Also I think the link for "Web Security and You" is popping up the box for "Caching Best Practices"

![image](https://f.cloud.github.com/assets/1890796/1490015/fbf0bba2-4788-11e3-946d-4090050008db.png)

That's all I have found.

**Comment by johannac** [comment]
Thanks for reporting this! Was an issue with non-unique IDs affecting all the speakers who are doing more than one talk. Have fixed now.

**Comment by levofski** [comment]
Cheers!
