### ISSUE TITLE
BUG - there is small link bug for twitter link

### ISSUE THREAD

**Issue by sandykadam** [phplondon/phpukconference#65]
I just spotted a small link issue on the official website of phpcon. In footer twitter feeds there is link to see old phpuk18 tweets but the link is pointing to phpuk17 tweets.

it says **"View more searching #phpuk18 on Twitter"** but link points to **https://twitter.com/search?q=phpuk17**

**Comment by johannac** [comment]
Thank you for reporting, this has been fixed!
