### ISSUE TITLE
Venue page = 404

### ISSUE THREAD

**Issue by n8kowald** [phplondon/phpukconference#68]
https://www.phpconference.co.uk/venue/ - linked to in footer

<img width="696" alt="Screen Shot 2020-02-14 at 2 41 01 pm" src="https://user-images.githubusercontent.com/1101518/74500833-1ce8c080-4f38-11ea-83c9-d31e372a5441.png">

**Comment by skinymikeofdoom** [comment]
I had the same issue, if anyone is looking for the address:

[52 Chiswell Street
London, EC1Y 4SD](https://www.google.com/maps/place/The+Brewery/@51.5208748,-0.0914527,15z/data=!4m2!3m1!1s0x0:0xb8605024f3360e44?sa=X&ved=2ahUKEwi5-dGV9dvnAhWdAp0JHV_tAJ0Q_BIwE3oECBAQCA)

**Comment by johannac** [comment]
Thank you for reporting, this has been fixed!
