### ISSUE TITLE
Create archive pages for previous years

### ISSUE THREAD

**Issue by johannac** [phplondon/phpukconference#9]
We have content for each year of the conference going back to 2006, however each year is pretty much in a different design/format from switching sites so often. Would like to gather this all up and put it in the current jekyll site in nice semantic html, so that if we do move to a new site again in a couple years, it can just be reskinned with new css. I have done a couple years so far, but the remaining years have more content so need more work done. We should probably do this issue first so we can reuse the layouts and templates in the archive area https://github.com/phplondon/phpukconference/issues/8

**Comment by j-d** [comment]
I can try to do this. Where would I find the old files?

**Comment by johannac** [comment]
Awesome, that would be great @j-d ! I'm currently gathering up all the info from the previous site(s) which is kinda strewn all over the place, so it might be better to start on this one https://github.com/phplondon/phpukconference/issues/10 and we can move on to this one afterwards, I should have everything ready by then.
